### ISSUE TITLE
[QUESTION] Does Megatron-DeepSpeed run on AMD GPUs?

### ISSUE THREAD

**Issue by adammoody** [microsoft/Megatron-DeepSpeed#201]
Short question:
Does Megatron-DeepSpeed work on AMD systems, and if not, is AMD support in the plans?

Long version:
I have a system with AMD MI250 GPUs and DeepSpeed installed with pre-compiled ops built with ROCm v5.4.2.  I am trying to run the Megatron-DeepSpeed pretrain_gpt.py script using a recent clone of Megatron-DeepSpeed.git (Aug 8, 2023).  However, I run into a number of issues.

I see that a recent rebase with Nvidia's upstream Megatron-LM repo brought in some new apex module references.  For example, this one:

https://github.com/microsoft/Megatron-DeepSpeed/blob/712057c8bd4fbc090a3ab022c0c4d9931b3cfd71/megatron/model/fused_layer_norm.py#L22

There are other places that conditionally import apex modules if the device name matches "cuda" like:

https://github.com/microsoft/Megatron-DeepSpeed/blob/712057c8bd4fbc090a3ab022c0c4d9931b3cfd71/megatron/optimizer/clip_grads.py#L11-L14

That check evaluates to True on my AMD system.  However, I don't have the apex module installed in my environment.  I see the above code is in the "before_rebase" branch, so at least this bit is not new.

For now, I have disabled/commented out these apex references to attempt to fallback to non-apex alternative code paths.

Then I hit an error when Megatron-DeepSpeed attempts to compile megatron/fused_kernels/scaled_softmax_hip.hip:
```
/path/to/Megatron-DeepSpeed.git/megatron/fused_kernels/scaled_softmax_hip.hip:8:10: fatal error: 'cuda_profiler_api.h' file not found
#include <cuda_profiler_api.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx90a.
```
I see that same file is included in some other fused_kernel code, but it is guarded like so:
```
diff --git a/megatron/fused_kernels/scaled_softmax_cuda.cu b/megatron/fused_kernels/scaled_softmax_cuda.cu
index ecc6eb0..90e1c9f 100644
--- a/megatron/fused_kernels/scaled_softmax_cuda.cu
+++ b/megatron/fused_kernels/scaled_softmax_cuda.cu
@@ -4,7 +4,9 @@
 #include <cuda.h>
 #include <cuda_runtime.h>
 #include <cuda_fp16.h>
+#ifndef __HIP_PLATFORM_HCC__
 #include <cuda_profiler_api.h>
+#endif
 #include <ATen/cuda/CUDAContext.h>
 #include <torch/extension.h>
 #include "scaled_masked_softmax.h"
```

Applying the above patch gets past the compilation problem, but then I hit a third problem:
```
  File "/path/to/Megatron-DeepSpeed.git/megatron/initialize.py", line 303, in set_jit_fusion_options
    torch._C._jit_set_nvfuser_enabled(True)
RuntimeError: Running CUDA fuser is only supported on CUDA builds.
```

I can seem to get by that issue if I comment out that line, but then I hit another problem that seems to be related to apex.

Is apex required in Megatron-DeepSpeed, or is it optional?

Does apex work properly on AMD systems?

I did find https://github.com/ROCmSoftwarePlatform/apex#rocm which suggests that it is available, though I'm getting a build error when trying to install.

Does Megatron-DeepSpeed work yet on AMD systems, and if not, is AMD support in the plans?

Thanks.

**Comment by tjruwase** [comment]
@adammoody, thanks for your question. It is awesome to see you running Megatron-DeepSpeed on AMD. Yes, DeepSpeed provides first class support for AMD. You might find this blog a useful read:
https://cloudblogs.microsoft.com/opensource/2022/03/21/supporting-efficient-large-model-training-on-amd-instinct-gpus-with-deepspeed/.

FYI @rraminen and @jithunnair-amd, who have been driving performance optimizations for Megatron-DeepSpeed on AMD.

**Comment by tjruwase** [comment]
@adammoody, it would be great for the community if you could document your experience. For example, if you could create an example with tutorial about how to train on AMD GPUs, we would be happy to put that in an AMD_support folder under examples_deepspeed. This will be very helpful to other users who are ramping up on AMD GPUs. We are also open to suggestions of how best you think the community can benefit from your experience. Thanks so much for your consideration.

**Comment by conglongli** [comment]
@adammoody @rraminen and @jithunnair-amd, as @tjruwase said we totally welcome your collective contributions to create a new "AMD_support" folder under https://github.com/microsoft/Megatron-DeepSpeed/tree/main/examples_deepspeed to host any example or tutorial of training on AMD GPUs. You can even create a PR with any half-baked examples/documents as long as clearly documenting any remaining issues. This will be really helpful for other groups to help improve it together in parallel.

**Comment by jithunnair-amd** [comment]
@adammoody Thanks for looking into Megatron-DeepSpeed with AMD GPUs. To understand your working environment better, are you using PyTorch wheels or a rocm/pytorch docker image (which comes with pytorch and apex pre-installed)?

**Comment by adammoody** [comment]
Sure, I'm happy to write up things as I figure them out.

@jithunnair-amd , I am using the ROCm-5.4.2 wheel from PyTorch installed into a virtualenv:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
```

I have built DeepSpeed from source:
```
git clone https://github.com/microsoft/DeepSpeed.git
cd DeepSpeed
rm -rf build
export DISTUTILS_DEBUG=1
export __HIP_PLATFORM_HCC__
export __HIP_PLATFORM_AMD__
export HCC_AMDGPU_TARGET=gfx90a
export PYTORCH_ROCM_ARCH=gfx90a
export ROCM_HOME=/opt/rocm-5.4.2
DS_BUILD_OPS=1 DS_BUILD_SPARSE_ATTN=0 DS_BUILD_QUANTIZER=0 DS_BUILD_RANDOM_LTD=0 DS_BUILD_TRANSFORMER_INFERENCE=0 python3 setup.py bdist_wheel
pip3 install dist/deepspeed-0.9.3+49a73549-cp39-cp39-linux_x86_64.whl
```

After reading https://github.com/ROCmSoftwarePlatform/apex more carefully, it sounds like I should be able to get apex installed after all.  That would simplify some of the workarounds I listed above, so I'm trying to do that now.
```
# based on instructions from:  https://github.com/ROCmSoftwarePlatform/apex#linux
git clone https://github.com/ROCmSoftwarePlatform/apex.git
cd apex
pip3 install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
```

The apex build completes and it installs, but then it complains about a missing a libstc++.so symbol at runtime.
```
  File "/path/to/Megatron-DeepSpeed.git/megatron/optimizer/clip_grads.py", line 14, in <module>
    import amp_C
ImportError: /path/to/env/lib/python3.9/site-packages/amp_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```
```
>>:  c++filt _ZSt28__throw_bad_array_new_lengthv
std::__throw_bad_array_new_length()
```
My build must linking to a different libstdc++ than is what loaded in my runtime environment.  I'm currently trying to debug that mixup.

**Comment by adammoody** [comment]
I think I got past the undefined symbol problem.  My default system compiler is gcc-10.3.  The compile step references _ZSt28__throw_bad_array_new_lengthv, but the linking step leaves it as undefined in the resulting .so library.

If I switch to gcc-11.2, then the resulting library includes a definition for that symbol:
```
>>: nm apex/build/lib.linux-x86_64-cpython-39/amp_C.cpython-39-x86_64-linux-gnu.so | grep throw_bad_array
000000000001fef9 T _ZSt28__throw_bad_array_new_lengthv
```

The idea to try that came from https://www.spinics.net/lists/gcchelp/msg52737.html

**Comment by adammoody** [comment]
The next problem I see is:
```
3:   File "/path/to/Megatron-DeepSpeed.git/megatron/core/tensor_parallel/layers.py", line 540, in __init__
1:     raise RuntimeError(
1: RuntimeError: ColumnParallelLinear was called with gradient_accumulation_fusion set to True but the custom CUDA extension fused_weight_gradient_mlp_cuda module is not found. To use gradient_accumulation_fusion you must install APEX with --cpp_ext and --cuda_ext. For example: pip install --global-option="--cpp_ext" --global-option="--cuda_ext ." Note that the extension requires CUDA>=11. Otherwise, you must turn off gradient accumulation fusion
```
I see the ``fused_weight_gradient_mlp_cuda`` listed in the Nvidia apex build:

https://github.com/NVIDIA/apex/blame/6309120bf4158e552884427b18ebafc657d418df/setup.py#L347

However, I don't see ``fused_weight_gradient_mlp_cuda`` listed in the ROCm fork:

https://github.com/ROCmSoftwarePlatform/apex/blob/10c74820ada18fddd6899e2252589de85264588e/setup.py

@jithunnair-amd , is there a newer version of the ROCm fork of apex available?

**Comment by sajal-vt** [comment]
Hi, I am [Sajal Dash from ORNL](https://www.olcf.ornl.gov/directory/staff-member/sajal-dash/). Recently we have ported the Megatron-DeepSpeed codebase to run on Frontier (equipped with AMD MI250X GPUs). We have faced some similar problems but got around with some fixes.

For the APEX issue, we installed ROCM version of APEX from https://github.com/ROCmSoftwarePlatform/apex/wiki/Steps-to-install-Apex-on-ROCm. Then, we didn't have much trouble with APEX or CUDA related issues.

A few other things we had to modify:
1. Install deepspeed with prebuilt ops.
DS_BUILD_CPU_ADAM=1 DS_BUILD_FUSED_ADAM=1 DS_BUILD_FUSED_LAMB=1DS_BUILD_TRANSFORMER=1 DS_BUILD_AIO=1 DS_BUILD_UTILS=1 pip install deepspeed

2. Following from the earlier step, commented out jit_fusion options in megatron/training.py
Line 34: #from megatron.initialize import set_jit_fusion_options 
Line 100: #set_jit_fusion_options()

3. Add the following line to megatron/core/tensorparallel/layers.py – line 531, 
config.gradient_accumulation_fusion = False

4. In the launch script we had to set: 
export CUDA_DEVICE_MAX_CONNECTIONS=1

We have forked Megatron-DeepSpeed to Megatron-DeepSpeed-ORNL with the necessary changes. We are still making changes. We can share our porting effort with you if that deems beneficial.

**Comment by sajal-vt** [comment]
@adammoody The launch script to start with will be: launch_gpt_srun.frontier

**Comment by adammoody** [comment]
PR for the ``scaled_softmax_cuda.cu`` fused kernel patch described at the top of the issue: https://github.com/microsoft/Megatron-DeepSpeed/pull/219

**Comment by adammoody** [comment]
Thanks, @sajal-vt .  I've got Megatron-DeepSpeed training on my system now.

**Comment by conglongli** [comment]
> Thanks, @sajal-vt . I've got Megatron-DeepSpeed training on my system now.

@adammoody does this mean all the issues are fixed? And if so are you observing reasonable TFlops?

**Comment by adammoody** [comment]
I'm just getting underway testing performance.  I can see that the GPUs are pegged near 100% in my early tests, so it's off to a good start so far.

I still have to comment out the nvfuser line here or otherwise I get:
```
File "/path/to/Megatron-DeepSpeed.git/megatron/initialize.py", line 303, in set_jit_fusion_options
    torch._C._jit_set_nvfuser_enabled(True)
RuntimeError: Running CUDA fuser is only supported on CUDA builds.
```
I'm guessing that could be skipped for ROCm users?

If possible, it would help if the ROCm apex could be updated to match the latest Nvidia apex.  Right now we have to disable the gradient accumulation fusion kernel, see https://github.com/microsoft/Megatron-DeepSpeed/issues/201#issuecomment-1672407873

@sajal-vt may be aware of more issues.

**Comment by conglongli** [comment]
> I still have to comment out the nvfuser line here or otherwise I get: I'm guessing that could be skipped for ROCm users?

@adammoody skipping it for non-NVIDIA sounds good to me, feel free to create a PR.

> If possible, it would help if the ROCm apex could be updated to match the latest Nvidia apex. Right now we have to disable the gradient accumulation fusion kernel, see https://github.com/microsoft/Megatron-DeepSpeed/issues/201#issuecomment-1672407873

@jithunnair-amd @rraminen could AMD help on this?

**Comment by rraminen** [comment]
@adammoody, is it possible to use Megatron-DeepSpeed from https://github.com/microsoft/Megatron-DeepSpeed/commit/f01c9e6e1ede00bb4e2441c04b86b5f56365bdff commit on AMD as a workaround while we work on the proper fix?

cc: @jithunnair-amd

**Comment by adammoody** [comment]
> > I still have to comment out the nvfuser line here or otherwise I get: I'm guessing that could be skipped for ROCm users?
> 
> @adammoody skipping it for non-NVIDIA sounds good to me, feel free to create a PR.

I've got a PR here: https://github.com/microsoft/Megatron-DeepSpeed/pull/220

**Comment by adammoody** [comment]
> @adammoody, is it possible to use Megatron-DeepSpeed from [f01c9e6](https://github.com/microsoft/Megatron-DeepSpeed/commit/f01c9e6e1ede00bb4e2441c04b86b5f56365bdff) commit on AMD as a workaround while we work on the proper fix?
> 
> cc: @jithunnair-amd

Thanks, @rraminen .  Actually, with some help from @sajal-vt , we have the latest version of Megatron-DeepSpeed running on AMD with a few work arounds.  Would you mind providing feedback on PR https://github.com/microsoft/Megatron-DeepSpeed/pull/220 ?

**Comment by conglongli** [comment]
> > @adammoody, is it possible to use Megatron-DeepSpeed from [f01c9e6](https://github.com/microsoft/Megatron-DeepSpeed/commit/f01c9e6e1ede00bb4e2441c04b86b5f56365bdff) commit on AMD as a workaround while we work on the proper fix?
> > cc: @jithunnair-amd
> 
> Thanks, @rraminen . Actually, with some help from @sajal-vt , we have the latest version of Megatron-DeepSpeed running on AMD with a few work arounds. Would you mind providing feedback on PR #220 ?

@adammoody @rraminen I'm going to approve and merge https://github.com/microsoft/Megatron-DeepSpeed/pull/220 because I personally think option 2 is the current best solution. For option 1 dropping this line, we cannot assume PyTorch will always do the right thing. For option 3 using something like `is_rocm_pytorch()`, there is concern that DeepSpeed is also in the progress of supporting other hardware. But I'm open to more feedback and better solution.

**Comment by rraminen** [comment]
I agree with @conglongli

**Comment by adammoody** [comment]
Yet another option for the nvfuser workaround would be to fallback to the "else" case.  This apparently configures things for the "legacy" pytorch fuser.

https://github.com/microsoft/Megatron-DeepSpeed/blob/24888f1c79f3fcb4d66e559bb4c4ac4621580c82/megatron/initialize.py#L309-L314

It looks like some of the values are set to the opposite of what is used in the "if nvfuser" branch.  Would that be better?

**Comment by conglongli** [comment]
> Yet another option for the nvfuser workaround would be to fallback to the "else" case. This apparently configures things for the "legacy" pytorch fuser.
> 
> https://github.com/microsoft/Megatron-DeepSpeed/blob/24888f1c79f3fcb4d66e559bb4c4ac4621580c82/megatron/initialize.py#L309-L314
> 
> It looks like some of the values are set to the opposite of what is used in the "if nvfuser" branch. Would that be better?

I think this depends on which way provides better performance on AMD GPUs. If @adammoody you find that this another option is better, I'm totally fine for making the changes.

**Comment by jithunnair-amd** [comment]
> However, I don't see fused_weight_gradient_mlp_cuda listed in the ROCm fork:
> https://github.com/ROCmSoftwarePlatform/apex/blob/10c74820ada18fddd6899e2252589de85264588e/setup.py
> @jithunnair-amd , is there a newer version of the ROCm fork of apex available?

That's the current version of ROCm apex, but we will try to add support for this particular extension.

**Comment by sajal-vt** [comment]
Not sure if it's an entirely related question. Though with my porting, we can run large models up to 1T parameters, every now and then I run into "Memory access fault by GPU node-X (Agent handle: 0x7e929d0) on address 0x7fec2dc38000. Reason: Unknown." error for certain micro_batch_size and global_batch_size or the model configurations. After some internet search, I see that other people faced something similar, but all of them are on ROCM hardware. Any idea how to debug/solve it?

**Comment by adammoody** [comment]
@sajal-vt , I haven't seen those on our MI250 cards yet, but I've only recently started to run jobs.  I have previously encountered similar messages on a system with older AMD cards:
```
Memory access fault by GPU node-2 (Agent handle: 0x580db0) on address 0x18000. Reason: Page not present or supervisor privilege.
```

On that system, we found that updating to PyTorch built with ROCm-5.5 avoided them, which can be installed from the nightly release.

```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5
```

Alternatively, we found that we could work around the problem in PyTorch built with ROCM-5.4 by setting:
```
export HSA_DISABLE_CACHE=1
```

However, that can significantly reduce performance.  I found that variable along with others listed here:

https://rocmdocs.amd.com/en/latest/how_to/system_debugging.html#rocr-level-environment-variables-for-debug

I still don't know the underlying cause or why either of those work arounds happened to resolve the problem.

**Comment by conglongli** [comment]
@adammoody @sajal-vt FYI I merged this PR from AMD @rraminen https://github.com/microsoft/Megatron-DeepSpeed/pull/232

**Comment by sajal-vt** [comment]
> @sajal-vt , I haven't seen those on our MI250 cards yet, but I've only recently started to run jobs. I have previously encountered similar messages on a system with older AMD cards:
> 
> ```
> Memory access fault by GPU node-2 (Agent handle: 0x580db0) on address 0x18000. Reason: Page not present or supervisor privilege.
> ```
> 
> This happened during the first collective (`dist.barrier()`) after all procs had successfully returned from `torch.dist.init_process_group()`.
> 
> On that system, we found that updating to PyTorch built with ROCm-5.5 avoided them, which can be installed from the nightly release.
> 
> ```
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5
> ```
> 
> Alternatively, we found that we could work around the problem in PyTorch built with ROCM-5.4 by setting:
> 
> ```
> export HSA_DISABLE_CACHE=1
> ```
> 
> However, that can significantly reduce performance. I found that variable along with others listed here:
> 
> https://rocmdocs.amd.com/en/latest/how_to/system_debugging.html#rocr-level-environment-variables-for-debug
> 
> I still don't know the underlying cause or why either of those work arounds happened to resolve the problem.

@adammoody : My error seems to be very non-specific (Reason: unknown). So, I am tried to set export HSA_DISABLE_CACHE=1, it didn't solve the issue. Then I installed the nightly pytorch with rocm/5.5. But, now apex would not install. I didn't anticipate having trouble with apex installation, so have to spend more time on that. But if you faced any problem with apex installation, I would love to know how you solved it.

**Comment by adammoody** [comment]
@sajal-vt , I am seeing similar apex build errors with ROCm-5.5 (and ROCm-5.6).  For that matter, it also fails to build now with ROCm-5.4, which used to work for me a few weeks back.  I think there are multiple compile issues here.  I've opened a ticket on the apex github https://github.com/ROCmSoftwarePlatform/apex/issues/115

**Comment by manmukhe** [comment]
@adammoody and all: is there a docker with all the right environment to run a data parallel training job on AMD MI250 cluster?

**Comment by jithunnair-amd** [comment]
> @adammoody and all: is there a docker with all the right environment to run a data parallel training job on AMD MI250 cluster?

@manmukhe Are you looking for a docker image which has apex/DeepSpeed/Megatron-DeepSpeed for ROCm pre-installed? Trying to understand what the "right environment" is for you.
We publish [rocm/pytorch](https://hub.docker.com/r/rocm/pytorch/) docker images for every ROCm release which has a compatible apex pre-installed.
We also publish [rocm/deepspeed](https://hub.docker.com/r/rocm/deepspeed/) docker images that has a compatible apex and DeepSpeed pre-installed.

**Comment by yuqie** [comment]
> Not sure if it's an entirely related question. Though with my porting, we can run large models up to 1T parameters, every now and then I run into "Memory access fault by GPU node-X (Agent handle: 0x7e929d0) on address 0x7fec2dc38000. Reason: Unknown." error for certain micro_batch_size and global_batch_size or the model configurations. After some internet search, I see that other people faced something similar, but all of them are on ROCM hardware. Any idea how to debug/solve it?

@sajal-vt Hi, have you solved this problem? I also encounter this error when run megatron-deepspeed with llama2-7b on a single GPU, but it's ok when I try gpt-1.3B.
